# Generated by Django 4.1.7 on 2023-03-22 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookGenre',
        ),
        migrations.DeleteModel(
            name='BookPublishingHouse',
        ),
        migrations.DeleteModel(
            name='BookSeries',
        ),
    ]
