# Generated by Django 4.1.7 on 2023-03-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0002_delete_bookgenre_delete_bookpublishinghouse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Book name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Book image')),
                ('publishing_year', models.CharField(max_length=11, verbose_name='Publishing year')),
                ('pages', models.IntegerField(verbose_name='Pages')),
                ('binding', models.CharField(max_length=15, verbose_name='Binding')),
                ('format', models.CharField(max_length=7, verbose_name='Format')),
                ('isbn', models.CharField(max_length=30, verbose_name='ISBN')),
                ('weight', models.IntegerField(help_text='Weight in grams', verbose_name='Weight')),
                ('age_restriction', models.IntegerField(verbose_name='Age restriction')),
                ('date_of_addition', models.DateField(verbose_name='Date of addition')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('description', models.TextField(blank=True, null=True)),
                ('author', models.ManyToManyField(to='references.bookauthor')),
            ],
        ),
    ]
