name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build -t book_service:latest .
    - name: Run tests
      run: docker run --rm -w /book_service/src -e DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY book_service python manage.py test
